### ISSUE TITLE
Is there a way to define a prefix?

### ISSUE THREAD

**Issue by stefl** [emortlock/tailwind-react-ui#55]
Hi Ed, 

I'm trying to using this project for a prototype that I'm building.

Part of that prototype has Bootstrap components, and there are a few clashes with Tailwind classes.

Tailwind supports a `prefix` option in config which prefixes all generated classes to avoid that problem.

Is there a way to define a prefix for this library so that I can take advantage of that feature?

Stef

**Comment by emortlock** [comment]
Not currently, but it's a good point - should hopefully be able to do it by making [Base](https://github.com/emortlock/tailwind-react-ui/tree/master/src/components/primitives/Base.jsx) aware of the theme object and have it as a param in there which can be passed to [getTailwindClassNames](https://github.com/emortlock/tailwind-react-ui/tree/master/src/components/tailwind/getTailwindClassNames.js). Will give it a bash when I'm able (would obviously be happy to accept a PR too if you fancy it)

**Comment by emortlock** [comment]
Hey Stef, in v0.8.0+ you should now be able to define `prefix: 'tw-'` as part of the theme config & have that propagate through to all util classes
